<?php
/**
 * InfrastructuralApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  RtgConnector\RtgConnectBundle
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * RTG-Portal
 *
 * The RTG-Portal API is an interface for selected RTG-Shop customers.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: fabian.kaufmann@picard.de
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.5.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace RtgConnector\RtgConnectBundle\Test\Api;

use \RtgConnector\RtgConnectBundle\Configuration;
use \RtgConnector\RtgConnectBundle\ApiException;
use \RtgConnector\RtgConnectBundle\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * InfrastructuralApiTest Class Doc Comment
 *
 * @category Class
 * @package  RtgConnector\RtgConnectBundle
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class InfrastructuralApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for checkConnection
     *
     * checkConnection.
     *
     */
    public function testCheckConnection()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getCarriers
     *
     * getCarriers.
     *
     */
    public function testGetCarriers()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getLanguages
     *
     * getLanguages.
     *
     */
    public function testGetLanguages()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getOrderStatuscodes
     *
     * getOrderStatuscodes.
     *
     */
    public function testGetOrderStatuscodes()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getProductCategories
     *
     * getProductCategories.
     *
     */
    public function testGetProductCategories()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getProductManufacturers
     *
     * getProductManufacturers.
     *
     */
    public function testGetProductManufacturers()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateRequestStatus
     *
     * updateRequestStatus.
     *
     */
    public function testUpdateRequestStatus()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
